#!/bin/bash
set -e

DATASET=${1:-data/biochem_xdr_full.json}
GOLD=${2:-data/biochem_xdr_gold.json}
RESULTS=${3:-results}
COOC=${4:-cooccurrence_results}
TIER_FILE=${5:-configs/tier_aggregate_calibrated.csv}
OUTPUT=${6:-analysis_outputs}
FIGURES=${7:-figures_output}

mkdir -p "$OUTPUT" "$FIGURES"

# tier_aggregate_calibrated.csv is generated by tiers/tier_analysis.py
# after running the full MCQ evaluation. A pre-computed copy for the
# paper results is included in configs/.
if [ ! -f "$TIER_FILE" ]; then
    echo "ERROR: $TIER_FILE not found."
    echo "Run: python tiers/tier_analysis.py $RESULTS configs/"
    exit 1
fi

echo "=== Table 1: Main Results ==="
python analysis/main_results.py "$RESULTS" "$OUTPUT"

echo "=== Appendix Tables ==="
python analysis/appendix_tables.py "$RESULTS" "$COOC" "$GOLD" "$TIER_FILE" "$OUTPUT"

echo "=== Gold Subset Results ==="
python gold/gold_results.py "$GOLD" "$RESULTS" "$OUTPUT"

echo "=== Figures ==="
python figures/generate_all_figures.py "$RESULTS" "$DATASET" "$TIER_FILE" "$FIGURES"

echo "Done. Outputs in $OUTPUT and $FIGURES"